Add bookings
green-rail/java-shareit pull request #2
Opened 2023-07-12 14:46 UTC by green-rail

2023-07-13 10:07 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-07-13 10:07 UTC, LexLippi commented on src/main/resources/schema.sql
> +  available BOOLEAN,
`not null`

2023-07-13 10:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoMapper.java
> +                userDto.getId() == null ? -1L : userDto.getId(),
Может просто завести объектный тип данных?
Тогда `null` будет допустим, `-1` выглядит, как не очень красивый костыль

2023-07-13 10:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        //}
такое стоит удалять, если больше нигде не нужно. иначе это захламляет код и потом сложно с этим работать

2023-07-13 10:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        //boolean anyComplete = bookings.stream().anyMatch(b -> b.getStatus().equals(BookingStatus.APPROVED));
Про комментарии такого рода уже писал

2023-07-13 10:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            var res = ItemDtoMapper.toDto(item, comments, last, next);
Зачем нам промежуточная переменная с не очень информативным названием?

2023-07-13 10:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            BookingDto last = null;
с помощью тернареого оператора можно совместить с инициализацией

2023-07-13 10:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            var l = bookings.stream().filter(b -> b.getStart().isBefore(now) && !b.getStatus().equals(BookingStatus.REJECTED))
Не ясно, что это за переменные с таким названием

2023-07-13 10:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            var l = bookings.stream().filter(b -> b.getStart().isBefore(now) && !b.getStatus().equals(BookingStatus.REJECTED))
Переменные в лямбда-выражениях тоже нормальные переменные и не очень хорошо давать им однобуквенные названия

2023-07-13 10:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoValidator.java
> +        String message = "";
для этого стоит использовать класс `StringBuilder`

2023-07-13 15:48 UTC, green-rail commented on src/main/resources/schema.sql
> +  request_id BIGINT,
Это айди из будущего функционала, по гайду сказали добавить. Пока убрал

2023-07-13 15:49 UTC, green-rail commented
Спасибо за фидбек!

2023-07-14 06:55 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-07-24 02:30 UTC, merged